<!--<?xml version="1.0"?>-->
<robot  xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:arg name="keyboard_name" default="keyboard"/>
    <xacro:arg name="key_size_x" default="0.1"/>
    <xacro:arg name="key_size_y" default="0.1"/>
    <xacro:arg name="key_size_z" default="0.001"/>
    <xacro:arg name="keyboard_rows" default="4"/>
    <xacro:arg name="keyboard_cols" default="3"/>

    <xacro:property name="keyboard_name" value="$(arg keyboard_name)"/>
    <xacro:property name="key_size_x" value="$(arg key_size_x)"/>
    <xacro:property name="key_size_y" value="$(arg key_size_y)"/>
    <xacro:property name="key_size_z" value="$(arg key_size_z)"/>
    <xacro:property name="keyboard_rows" value="$(arg keyboard_rows)"/>
    <xacro:property name="keyboard_cols" value="$(arg keyboard_cols)"/>
    <xacro:property name="kp" value="1e13"/>
    <xacro:property name="kd" value="1"/>
    
    <xacro:property name="key_names"        value="${['none_0', 'yaw_pos', 'yaw_neg', 'z_neg', 'x_pos',  'z_pos',  'y_pos',  'x_neg', 'y_neg', 'none_9','open_gripper', 'close_gripper']}" />
<!--    <xacro:property name="key_colors"       value="${['dark_blue', 'light_red', 'light_blue', 'light_green', 'dark_red', 'dark_green']}" />-->
    <xacro:property name="key_colors"       value="${['white', 'white', 'white', 'white', 'white', 'white', 'white', 'white', 'white', 'white', 'white', 'white']}" />
    <xacro:property name="key_colors_gazebo"       value="${['Gazebo/Blue', 'Gazebo/Red', 'Gazebo/Blue', 'Gazebo/Green', 'Gazebo/Red', 'Gazebo/Green', 'Gazebo/Blue', 'Gazebo/Blue', 'Gazebo/FlatBlack', 'Gazebo/DarkGrey', 'Gazebo/DarkGrey', 'Gazebo/FlatBlack']}" />

    <xacro:property name="top_right_corner_x" value="${keyboard_rows/2 * key_size_x}"/>
    <xacro:property name="top_right_corner_y" value="${keyboard_cols/2 * key_size_y}"/>
    
    <material name="light_red">
        <color rgba="1.0 0.0 0.0 1"/>
    </material>
    <material name="dark_red">
        <color rgba="0.5 0.0 0.0 1"/>
    </material>
    <material name="light_green">
        <color rgba="0.0 1.0 0.0 1"/>
    </material>
    <material name="dark_green">
        <color rgba="0.0 0.5 0.0 1"/>
    </material>
    <material name="light_blue">
        <color rgba="0.0 0.0 1.0 1"/>
    </material>
    <material name="dark_blue">
        <color rgba="0.0 0.0 0.5 1"/>
    </material>
    <material name="trasparent">
        <color rgba="0.0 0.0 0.0 0"/>
    </material>
    <material name="white">
        <color rgba="1.0 1.0 1.0 1"/>
    </material>
</robot>
