<?xml version="1.0" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="table">

    <xacro:arg name="surface_name" default="surface"/>
    <xacro:arg name="surface_size_x" default="0.8"/>
    <xacro:arg name="surface_size_y" default="1.5"/>
    <xacro:arg name="surface_size_z" default="0.03"/>
    <xacro:arg name="surface_high" default="0.8"/>
    <xacro:arg name="surface_mass" default="30"/>
    <xacro:arg name="leg_mass" default="2"/>
    <xacro:arg name="surface_gazebo_color" default="Gazebo/Wood"/>
    <xacro:arg name="leg_gazebo_color" default="Gazebo/Gray"/>
    <xacro:arg name="kp" default="1e13"/>
    <xacro:arg name="kd" default="1"/>
	
    <!-- marker related -->	    
    <xacro:arg name="markers" default="false"/>
    <xacro:arg name="marker_size" default="0.18"/>
    <xacro:arg name="marker_id" default="0"/>
    <xacro:arg name="marker_pos" default="2"/>
    <xacro:arg name="marker_thickness" default="0.00001"/>
    
    <xacro:property name="surface_size_x" value="$(arg surface_size_x)"/>
    <xacro:property name="surface_size_y" value="$(arg surface_size_y)"/>
    <xacro:property name="surface_size_z" value="$(arg surface_size_z)"/>
    <xacro:property name="surface_mass" value="$(arg surface_mass)"/>
    <xacro:property name="surface_high" value="$(arg surface_high)"/>
    <xacro:property name="leg_mass" value="$(arg leg_mass)"/>
    <xacro:property name="surface_gazebo_color" value="$(arg surface_gazebo_color)"/>
    <xacro:property name="leg_gazebo_color" value="$(arg leg_gazebo_color)"/>
    <xacro:property name="kp" value="$(arg kp)"/>
    <xacro:property name="kd" value="$(arg kd)"/>
    <xacro:property name="surface_name" value="$(arg surface_name)"/>
    
    <!-- marker related -->
    <xacro:property name="markers" value="$(arg markers)"/>
    <xacro:property name="marker_size" value="$(arg marker_size)"/>
    <xacro:property name="marker_id" value="$(arg marker_id)"/>
    <xacro:property name="marker_pos" value="$(arg marker_pos)"/>
    <xacro:property name="marker_thickness" value="$(arg marker_thickness)"/>

    <material name="${surface_gazebo_color}">
        <color rgba="1.0 1.0 1.0 1.0"/>
    </material>
    <material name="${leg_gazebo_color}">
        <color rgba=".3 .3 .3 1.0"/>
    </material>
    
    <origin rpy="0 0 0" xyz="0 0 ${surface_high-surface_size_z/2}"/>
    
    <link name="${surface_name}">
        <inertial>
            <mass value="${surface_mass}" />
            <inertia  ixx="${0.083 * surface_mass * (surface_size_y*surface_size_y + surface_size_z*surface_size_z)}" ixy="0.0"  ixz="0.0"  
                      iyy="${0.083 * surface_mass * (surface_size_x*surface_size_x + surface_size_z*surface_size_z)}"  iyz="0.0"  
                      izz="${0.083 * surface_mass * (surface_size_x*surface_size_x + surface_size_y*surface_size_y)}" />
        </inertial>

        <collision>
            <geometry>
                <box size="${surface_size_x} ${surface_size_y} ${surface_size_z}"/>
            </geometry>
        </collision>
        
        <visual>
            <geometry>
                <box size="${surface_size_x} ${surface_size_y} ${surface_size_z}"/>
            </geometry>
            <material name="${surface_gazebo_color}"/>
        </visual>
    </link>
    
    <gazebo reference="${surface_name}">
        <mu1>0.8</mu1>
        <mu2>0.8</mu2>
        <kp>${kp}</kp>
        <kd>${kd}</kd>	
        <material>${surface_gazebo_color}</material>
    </gazebo>
    
    <link name="table_base_footprint"></link>
    <joint name="table_base_footprint_joint" type="fixed">
        <parent link="${surface_name}"/>
        <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-surface_high+(surface_size_z/2)}"/>
        <child link="table_base_footprint"/>
    </joint>
    
    <link name="${surface_name}_top"></link>
    <joint name="${surface_name}_top_joint" type="fixed">
        <parent link="${surface_name}"/>
        <origin rpy="0.0 0.0 0.0" xyz="0 0 ${surface_size_z/2}"/>
        <child link="${surface_name}_top"/>
    </joint>
    
    <!-- LEGS -->
    <xacro:macro name="table_leg" params="name">
    <link name="${name}">
    
        <inertial>
            <mass value="${leg_mass}" />
            <inertia    ixx="${0.083 * leg_mass * (3*0.02*0.02 + (surface_high - surface_size_z)*(surface_high - surface_size_z))}"  ixy="0.0"  ixz="0.0"  
                        iyy="${0.083 * leg_mass * (3*0.02*0.02 + (surface_high - surface_size_z)*(surface_high - surface_size_z))}"  iyz="0.0"  
                        izz="${0.5 * leg_mass * 0.02 * 0.02}" />
        </inertial>

        <collision>
            <geometry>
                <cylinder radius="0.02" length="${surface_high - surface_size_z}"/>
            </geometry>
        </collision>
        
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="0.02" length="${surface_high - surface_size_z}"/>
            </geometry>
            <material name="${leg_gazebo_color}"/>
        </visual>
   
    </link>
    <gazebo reference="${name}">
        <mu1>0.8</mu1>
        <mu2>0.8</mu2>
        <kp>${kp}</kp>
        <kd>${kd}</kd>	
        <material>${leg_gazebo_color}</material>
    </gazebo>
    </xacro:macro>

    <xacro:table_leg name="front_left_leg"/>
    <xacro:table_leg name="front_right_leg"/>
    <xacro:table_leg name="back_right_leg"/>
    <xacro:table_leg name="back_left_leg"/>
    
    <!-- JOINTS -->
    <joint name="front_left_leg_joint" type="fixed">
        <parent link="${surface_name}"/>
        <origin rpy="0.0 0.0 0.0" xyz="${surface_size_x/2 - 0.02} ${surface_size_y/2 - 0.02} ${-surface_high/2}"/>
        <child link="front_left_leg"/>
    </joint>
    <joint name="front_right_leg_joint" type="fixed">
        <parent link="${surface_name}"/>
        <origin rpy="0.0 0.0 0.0" xyz="${surface_size_x/2 - 0.02} ${-surface_size_y/2 + 0.02} ${-surface_high/2}"/>
        <child link="front_right_leg"/>
    </joint>
    <joint name="back_right_leg_joint" type="fixed">
        <parent link="${surface_name}"/>
        <origin rpy="0.0 0.0 0.0" xyz="${-surface_size_x/2 + 0.02} ${-surface_size_y/2 + 0.02} ${-surface_high/2}"/>
        <child link="back_right_leg"/>
    </joint>
    <joint name="back_left_leg_joint" type="fixed">
        <parent link="${surface_name}"/>
        <origin rpy="0.0 0.0 0.0" xyz="${-surface_size_x/2 + 0.02} ${surface_size_y/2 - 0.02} ${-surface_high/2}"/>
        <child link="back_left_leg"/>
    </joint>
    
    <!--  ********************************* Links for arucos **********************************************************  -->
    <xacro:if value="${markers}">
   
    <xacro:if value="${marker_pos == 2}">
    <!-- center -->
    <link name="fiducial_${marker_id}">
      <visual>
        <origin xyz="0 0 ${-marker_thickness/2}" rpy="0 0 0" />
        <geometry>
          <box size="${marker_size} ${marker_size} ${marker_thickness}"/>
        </geometry>
        <material name="aruco_color_rviz">
            <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 ${-marker_thickness/2}" rpy="0 0 0" />
        <laser_retro>0</laser_retro>
        <max_contacts>10</max_contacts>
        <geometry>
          <box size="${marker_size} ${marker_size} ${marker_thickness}"/>
        </geometry>
      </collision>
    </link>
    <joint name="aruco_front_joint" type="fixed">
      <parent link="${surface_name}"/>
      <origin xyz="0 0 ${surface_size_z/2 + marker_thickness}" rpy="0 0 0"/>
      <child link="fiducial_${marker_id}"/>
    </joint>
    <gazebo reference="fiducial_${marker_id}">
        <visual name='visual'>
            <material>
                <script>
                    <uri>package://iit_gazebo_worlds_pkg/arucoBoxes/urdf/aruco_visual_marker_${marker_id}/materials/scripts</uri>
                    <uri>package://iit_gazebo_worlds_pkg/arucoBoxes/urdf/aruco_visual_marker_${marker_id}/materials/textures</uri>
                    <name>ArucoVisualMarker${marker_id}/Marker</name>
                </script>
                <ambient>1 1 1 1</ambient>
                <diffuse>1 1 1 1</diffuse>
                <specular>0 0 0 1</specular>
                <emissive>1 1 1 0</emissive>
                <shader type='vertex'>
                    <normal_map>__default__</normal_map>
                </shader>
                </material>
            <cast_shadows>1</cast_shadows>
            <transparency>0</transparency>
        </visual>
    </gazebo>
    </xacro:if>

    <!--north west-->
    <xacro:if value="${marker_pos == 0}">
    <link name="fiducial_${marker_id}">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${marker_size} ${marker_size} ${marker_thickness}"/>
        </geometry>
        <material name="aruco_color_rviz">
            <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <laser_retro>0</laser_retro>
        <max_contacts>10</max_contacts>
        <geometry>
          <box size="${marker_size} ${marker_size} ${marker_thickness}"/>
        </geometry>
      </collision>
    </link>
    <joint name="aruco_nw_joint" type="fixed">
      <parent link="${surface_name}"/>
      <origin xyz="${-(surface_size_x/2 + marker_thickness/2)} ${surface_size_y/2 - marker_size/2} ${surface_size_z/2 - marker_size/2}" rpy="0 1.5708 0"/>
      <child link="fiducial_${marker_id}"/>
    </joint>
    <gazebo reference="fiducial_${marker_id}">
        <visual name='visual'>
            <material>
                <script>
                    <uri>package://iit_gazebo_worlds_pkg/arucoBoxes/urdf/aruco_visual_marker_${marker_id}/materials/scripts</uri>
                    <uri>package://iit_gazebo_worlds_pkg/arucoBoxes/urdf/aruco_visual_marker_${marker_id}/materials/textures</uri>
                    <name>ArucoVisualMarker${marker_id}/Marker</name>
                </script>
                <ambient>1 1 1 1</ambient>
                <diffuse>1 1 1 1</diffuse>
                <specular>0 0 0 1</specular>
                <emissive>1 1 1 0</emissive>
                <shader type='vertex'>
                    <normal_map>__default__</normal_map>
                </shader>
            </material>
            <cast_shadows>1</cast_shadows>
            <transparency>0</transparency>
        </visual>
    </gazebo>
    
    </xacro:if>
    
    
    <xacro:if value="${marker_pos == 1}">
    <!--north center-->
    <link name="fiducial_${marker_id}">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${marker_size} ${marker_size} ${marker_thickness}"/>
        </geometry>
        <material name="aruco_color_rviz">
            <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <laser_retro>0</laser_retro>
        <max_contacts>10</max_contacts>
        <geometry>
          <box size="${marker_size} ${marker_size} ${marker_thickness}"/>
        </geometry>
      </collision>
    </link>
    <joint name="aruco_n_joint" type="fixed">
      <parent link="${surface_name}"/>
      <origin xyz="${-surface_size_x/2 + marker_thickness} 0 ${surface_size_z/2 - marker_size/2}" rpy="0 1.5708 0"/>
      <child link="fiducial_${marker_id}"/>
    </joint>
    <gazebo reference="fiducial_${marker_id}">
        <visual name='visual'>
            <material>
                <script>
                    <uri>package://iit_gazebo_worlds_pkg/arucoBoxes/urdf/aruco_visual_marker_${marker_id}/materials/scripts</uri>
                    <uri>package://iit_gazebo_worlds_pkg/arucoBoxes/urdf/aruco_visual_marker_${marker_id}/materials/textures</uri>
                    <name>ArucoVisualMarker${marker_id}/Marker</name>
                </script>
                <ambient>1 1 1 1</ambient>
                <diffuse>1 1 1 1</diffuse>
                <specular>0 0 0 1</specular>
                <emissive>1 1 1 0</emissive>
                <shader type='vertex'>
                    <normal_map>__default__</normal_map>
                </shader>
            </material>
            <cast_shadows>1</cast_shadows>
            <transparency>0</transparency>
        </visual>
    </gazebo>
    </xacro:if>
    
    </xacro:if>

</robot>

